from enum import Enum

class Status(Enum):
    INICIAL = "INICIAL"
    AGUARDANDO_OPCAO_1 = "AGUARDANDO_OPCAO_1"
    ERRO = "ERRO"
    ERRO_ENVIO = "ERRO_ENVIO"
    AGUARDANDO_DUVIDA_CONTABIL = "AGUARDANDO_DUVIDA_CONTABIL"
    AGUARDANDO_DETALHE_DESPESA = "AGUARDANDO_DETALHE_DESPESA"
    AGUARDANDO_CONCILIACAO = "AGUARDANDO_CONCILIACAO"
    AGUARDANDO_TIPO_PAGAMENTO = "AGUARDANDO_TIPO_PAGAMENTO"
    AGUARDANDO_MOVIMENTACAO = "AGUARDANDO_MOVIMENTACAO"
    AGUARDANDO_SUPERAVIT = "AGUARDANDO_SUPERAVIT"
    AGUARDANDO_RETENCAO = "AGUARDANDO_RETENCAO"
    AGUARDANDO_ALMOXARIFADO = "AGUARDANDO_ALMOXARIFADO"
    AGUARDANDO_ERRO_SIGEF = "AGUARDANDO_ERRO_SIGEF"
    AGUARDANDO_PERGUNTA = "AGUARDANDO_PERGUNTA"
    OUTRA_DUVIDA = "OUTRA_DUVIDA"
    AGUARDANDO_OUTRA_DUVIDA = "AGUARDANDO_OUTRA_DUVIDA"

class TypeUser(Enum):
    USER = "USER"
    BOT = "BOT"

class OriginService(Enum):
    TELEGRAM = "TELEGRAM"
    WHATSAPP = "WHATSAPP"